### ISSUE TITLE
x360ce issue

### ISSUE THREAD

**Issue by CeruleanSky** [Kaldaien/TSF#2]
x360ce the xinput emulator worked fine before tsfix, but after running tsfix_enabler I have been unable to use my controller.

I uninstalled TSFIX(or just deleted tsfix.ini & d3d9.ini) and the controller works again so something is going on with it. 

Here are some of the things I tried, maybe there is something I missed?

---

I have added `xinput1_3.dll`  to the d3d9 config:

```
[Import.xinput]
Architecture=Win32
Blacklist=tsfix_enabler.exe
Filename=xinput1_3.dll
Role=ThirdParty
When=Early
```

I have tried `When=Early,Lazy,Late,Proxy` , I have tried `Role=Plugin,ThirdParty`.

I had hoped `proxy` would cause Special K to tread DLL as if it were the one in C:\Windows...\xinput1_3.dll , but it didn't seem to load at all.
And tried just for testing `Role=xinput1_3` along with it.

I have used a fully qualified pathname to the dll aka `Filename=C:\somefolder\xinput1_3.dll`

I have also tried dinput8 which wasn't needed before just to test, and both xinput1_3 & dinput8 at the same time, and renaming xinput1_3.dll to x360ce_xinput1_3.dll.

I have deleted the line `Blacklist=tsfix_enabler.exe`

I have put `xinput1_3.dll` in the tales of directory and in my %temp% directory.  

I set all the TSFix.Input to false:

```
[TSFix.Input]
BlockLeftAlt=false
BlockLeftCtrl=false
BlockWindows=false
DisableTouch=false
PauseTouch=false

```

In each case the log says it is loading except for `proxy`

```

02/17/2016 13:03:04.823:   * Loading Early Custom Import tsfix.dll... success!
02/17/2016 13:03:05.075:   * Loading Early Custom Import xinput1_3.dll... success!
```

But it never seems to work.

**Comment by Kaldaien** [comment]
Proxy libraries are only for render-related DLLs. For example, if the game is D3D9, then my DLL has to be named d3d9.dll, and to make it compatible with other DLLs that work the same way that is what proxy is for. Otherwise, it would actually just forward all d3d9-related stuff that it didn't process to the D3D9 DLL in C:\Windows\SysWOW64...

This would have to be related to TSFix rather than Special K. The weird thing is, although I handle DInput8 and RawInput, I only handle keyboard/mouse. Controller input should not be affected at all. I'm not sure what's going on at the moment, I will have to take a look at it when I get a chance.

**Comment by CeruleanSky** [comment]
Might not be helpful, but both x360ce and TSF use minHook.  Also I saw you hook DirectInput8Create , [x360ce does also](https://github.com/x360ce/x360ce/blob/2f94d276eaccd83d4099989a8fdfc6812e1d5164/x360ce/InputHook/HookDI.cpp#L487) since its job is to turn directinput joysticks into xinput joysticks.  While this might not be the cause, it is probably the place to look first at what each is doing with that call.

If it helps determine the issue, gedosato works fine.

**Comment by Kaldaien** [comment]
I see, thank you.

I have an alternative method for hooking COM interfaces that I use in d3d9.dll. I will roll out a version of tsfix.dll tomorrow that uses that instead to see if it helps any.

**Comment by Kaldaien** [comment]
I have compiled an alternate version that does not use MinHook for COM interfaces, could you let me know if the results are any different?

[tsfix_althook.zip](https://github.com/Kaldaien/TSF/files/136959/tsfix_althook.zip)

**Comment by CeruleanSky** [comment]
Still does not work.  I'm not saying that minhook necessarily is the cause, because gedosata uses it also and works right, but what and the way they are being hooked might not be chaining right. 

I tried it without editing d3d9.ini. 

I then added the entry: 

```

[Import.xinput]
Architecture=Win32
Blacklist=tsfix_enabler.exe
Filename=xinput1_3.dll
Role=ThirdParty
When=Early
```

Also Role=Plugin and When=Early & Late

```

02/18/2016 16:25:46.704:   * Loading Early Custom Import tsfix.dll... success!
02/18/2016 16:25:46.748:   * Loading Early Custom Import xinput1_3.dll... success!

```

Here is the tsfix.log

```

02/18/2016 16:29:27.278: tsfix.log created
02/18/2016 16:29:27.463:  Stopping TabletInputService...  service not running.
02/18/2016 16:29:27.937:  [StutterFix] Scanned Namco Framerate Bug ("Limiter"): 005C9140h
02/18/2016 16:29:35.744:  % Caught D3D9 Swapchain :: Fullscreen=False  (1280x720@0 Hz)  [Device Window: 0x421254]
02/18/2016 16:29:35.753:  % Caught D3D9 Swapchain :: Fullscreen=False  (1280x720@0 Hz)  [Device Window: 0x421254]
02/18/2016 16:29:35.767:   # Found window in 8.1 seconds, installing keyboard hook...
02/18/2016 16:29:35.767:   * Installed keyboard hook for command console... 1 try (0 ms!)
02/18/2016 16:29:36.178:  [!] DirectInput8Create (0x65DE0000, 2048, ..., 65DFD268h, 00000000h)
02/18/2016 16:29:36.178:   Calling original function: (ret=S_OK)

02/18/2016 16:29:36.197:  [!] DirectInput8Create (0x400000, 2048, ..., 00E28CB0h, 00000000h)
02/18/2016 16:29:36.197:   Calling original function: (ret=S_OK)

02/18/2016 16:29:36.197:  [!] IDirectInput8::CreateDevice (157A253Ch, Default System Keyboard, 00B258FCh, 00000000h)
02/18/2016 16:29:36.197:   Calling original function: (ret=S_OK)

02/18/2016 16:29:36.632: SetWindowLongA (0x421254,  GWL_STYLE , 0x90080000)
02/18/2016 16:29:46.633:  % Caught D3D9 Swapchain :: Fullscreen=True  (1280x720@0 Hz)  [Device Window: 0x421254]
02/18/2016 16:29:53.112:  [!] IDirectInput8::CreateDevice (157A202Ch, Other Device, 0018F824h, 00000000h)
02/18/2016 16:29:53.112:   Calling original function: (ret=S_OK)

02/18/2016 16:29:53.193:  [!] IDirectInput8::CreateDevice (157A202Ch, Other Device, 0018F824h, 00000000h)
02/18/2016 16:29:53.193:   Calling original function: (ret=S_OK)
```

Then several hundred lines of these:

```

02/18/2016 16:34:14.909: GetDeviceState - cbData: 272, lpvData: 195FD81C
02/18/2016 16:34:14.909: GetDeviceState - cbData: 272, lpvData: 196006E4
02/18/2016 16:34:14.966: GetDeviceState - cbData: 272, lpvData: 195FD81C
02/18/2016 16:34:14.966: GetDeviceState - cbData: 272, lpvData: 196006E4

....

02/18/2016 16:34:31.079: GetDeviceState - cbData: 272, lpvData: 196006E4
02/18/2016 16:34:31.112: GetDeviceState - cbData: 272, lpvData: 195FD81C
02/18/2016 16:34:31.112: GetDeviceState - cbData: 272, lpvData: 196006E4
02/18/2016 16:34:31.318: Closing log file... 

```

**Comment by Kaldaien** [comment]
Is that log behavior new?

I have it setup to record any data structure > 256 bytes because I was concerned about keyboard overflow in the unmodified game while trying to diagnose the touchscreen keyboard problem.

I didn't really have DirectInput joystick input in mind though, and apparently that triggers my check. That's going to be removed for sure ;)

**Comment by Kaldaien** [comment]
Ideally, you are going to want the custom import to be loaded before TSFix. I have done a poor job documenting this, but the way that works for Early imports is in alphabetical order.

You could rename [Import.TSFix] to [Import.XXXTSFix] and that may solve some problems :P

**Comment by CeruleanSky** [comment]
Well your solution does load xinput1_3 before TSFIX as the included logs show, renamed it to Import zXXXTSFix.

It did not fix the issue, where the controller works fine with xinput1_3.dll and the game with or without gedosato , but the controller input doesn't work when tsfix is used in any circumstance.

I tried Role=PlugIn & Role=ThirdParty.
For both I did When=Early

Both TSFIX v0.4.1 and tsfix_althook produce a huge amount of GetDeviceState entries in the log. I haven't tried  a version earlier than 0.4.1.

[d3d9.log.txt](https://github.com/Kaldaien/TSF/files/137446/d3d9.log.txt)
[tsfix.log.txt](https://github.com/Kaldaien/TSF/files/137447/tsfix.log.txt)

**Comment by Kaldaien** [comment]
Can you grab the latest version of 0.4.2 and tell me if that fixes it? I have disabled hooking for third-party DLLs.

**Comment by CeruleanSky** [comment]
Still didn't work.  
I am willing to try and narrow down where the issue lies as long as you are willing.  

If easy to do, perhaps disable input blocking code?

------

What I did, in each of these cases it did not work.

Did a clean install of tsfix_enabler v0.4.2 
Tried the game.  
Added xinput1_3.dll to d3d9.ini and had it load before tsfix.dll  
Tried Role=Plugin & Thirdparty  

--------------

When removing tsfix or using Tales of Symphonia with or without GeDoSaTo, the controller & x360ce works.

**Comment by CeruleanSky** [comment]
Still didn't work.  
I am willing to test things out to narrow down where the issue lies as long as you are willing and have things to try.  

It did say it would not hook due to 3rd party dll, also I attached the full log:

```
02/19/2016 20:27:15.262:  >> A third-party DLL is manipulating DirectInput 8; will not hook.
02/19/2016 20:27:15.265:  [!] DirectInput8Create (0x400000, 2048, ..., 00E28CB0h, 00000000h)
02/19/2016 20:27:15.265:   Calling original function: (ret=S_OK)

```

---

What I did, in each of these cases it did not work.

Did a clean install of tsfix_enabler v0.4.2 
Tried the game.  
Added xinput1_3.dll to d3d9.ini and had it load before tsfix.dll  
Tried Role=Plugin & Thirdparty  

---

When removing tsfix or using Tales of Symphonia with or without GeDoSaTo, the controller & x360ce works.

[tsfix.log.txt](https://github.com/Kaldaien/TSF/files/138942/tsfix.log.txt)

**Comment by Kaldaien** [comment]
I believe it is actually going to be necessary to include dinput8.dll from x360ce in this equation. You're not loading all of the DLLs. I don't even touch XInput in fact. This is purely a dinput8 related problem.

Just drop x360ce's dinput8 dll straight into the ToS directory and TSFix will actually load that DLL. But it couldn't hurt to do it explicitly in d3d9.ini either.

**Comment by CeruleanSky** [comment]
Glad to try that out, unfortunately it did not work.  
If it doesn't take much time to make a test build that doesn't use dinput8 or keyboard hooking at all, I'll try it out. That would confirm we are looking in the right place.

---

When I added x360ce's dinput8.dll to the proper place the game works fine and the controller still works without TSFIX.exe
Then I tested that GeDoSaTo still works as it does similar things, then I exited GeDoSaTo

I tried then installed a clean TSFIX v0.4.2 and tried the game.
I tried then added an entry for dinput8.dll to load before tsfix.dll in d3d9.ini
I tried then added an entry for dinput8.dll & xinput1_3.dll to load before tsfix.dll in d3d9.ini

I also tried it with hard coded paths to make sure they loaded the proper dlls.

I tried both Role=Plugin & Role=ThirdParty

```

02/20/2016 15:04:40.477:   * Loading Early Custom Import dinput8.dll... success!
02/20/2016 15:04:40.479:   * Loading Early Custom Import xinput1_3.dll... success!
02/20/2016 15:04:40.482:   * Loading Early Custom Import tsfix.dll... success!
```

```
02/20/2016 15:04:50.059:   # Found window in 9.2 seconds, installing keyboard hook...
02/20/2016 15:04:50.059:   * Installed keyboard hook for command console... 1 try (0 ms!)
02/20/2016 15:04:50.729:  [!] DirectInput8Create (0x65DE0000, 2048, ..., 65DFD268h, 00000000h)
02/20/2016 15:04:50.729:   Calling original function: (ret=S_OK)

02/20/2016 15:04:50.767:  >> A third-party DLL is manipulating DirectInput 8; will not hook.
02/20/2016 15:04:50.771:  [!] DirectInput8Create (0x400000, 2048, ..., 00E28CB0h, 00000000h)
02/20/2016 15:04:50.771:   Calling original function: (ret=S_OK)

02/20/2016 15:04:50.792:  [!] IDirectInput8::CreateDevice (1991CA44h, Default System Keyboard, 00B258FCh, 00000000h)
02/20/2016 15:04:50.792:   Calling original function: (ret=S_OK)

02/20/2016 15:04:51.577: SetWindowLongA (0x3A0B5E,  GWL_STYLE , 0x90080000)
02/20/2016 15:05:01.578:  % Caught D3D9 Swapchain :: Fullscreen=True  (1280x720@0 Hz)  [Device Window: 0x3A0B5E]
02/20/2016 15:05:02.289:  [!] IDirectInput8::CreateDevice (1991C9FCh, Other Device, 0018F01Ch, 00000000h)
02/20/2016 15:05:02.289:   Calling original function: (ret=S_OK)

02/20/2016 15:05:02.500:  [!] IDirectInput8::CreateDevice (1991C9FCh, Other Device, 0018F01Ch, 00000000h)
02/20/2016 15:05:02.500:   Calling original function: (ret=S_OK)
```

**Comment by Kaldaien** [comment]
Okay, what I've done here is compile a version of 0.4.3 that:
1. Only hooks DirectInput8 when BlockWindows is set
2. Does not hook GetRawInputData if BlockLeftAlt is set

Between the two of those things, I cannot think of any other reason x360ce wouldn't work. My best guess is that it is the DirectInput8 stuff. But disabling that may cause issues with my background rendering feature -- input from the keyboard is likely to continue being processed even when the window is not active.

[tsfix-debug.zip](https://github.com/Kaldaien/TSF/files/139469/tsfix-debug.zip)

**Comment by CeruleanSky** [comment]
**Controller Works \o/ !!!!**

```
[TSFix.Input]
BlockLeftAlt=true
BlockWindows=false

```

```
[TSFix.Input]
BlockLeftAlt=false
BlockWindows=false

```

**Controller Doesn't Work**

```
[TSFix.Input]
BlockLeftAlt=true
BlockWindows=true

```

```
[TSFix.Input]
BlockLeftAlt=false
BlockWindows=true

```

**Comment by Kaldaien** [comment]
I've decided the solution is just to disable DirectInput hooking if the user doesn't request Windows Key blocking. I will actually turn that feature off by default in 0.4.4 and make a note of this.

It isn't necessary to hook DirectInput for anything other than blocking the Windows Key, all of the features designed to prevent the game from processing keyboard input while the game is in the background use `GetRawInputData (...)`.

<hr>

Incidentally, there was a new version of d3d9.dll in 0.4.3, but I don't think upgrading to it is necessary. It just fixes framerate limiting issues during <kbd>alt</kbd>+<kbd>tab</kbd>.

**Comment by CeruleanSky** [comment]
I just wanted to report that the below setting work excellently with x360ce.  BlockAllKeys prevents the keyboard from doing weird stuff when Tales of Symphonia is in the background, and if you are using a controller you don't really need keyboard input anyway.  And by keeping BlockWindows=False , the controller continues to work fine.

```
[TSFix.Input]
BlockLeftAlt=false
BlockLeftCtrl=false
BlockWindows=false
BlockAllKeys=true
```

**Comment by CeruleanSky** [comment]
I just wanted to report that the below setting work excellently with x360ce in case you were planning on modifying them at all.  BlockAllKeys prevents the keyboard from doing weird stuff when Tales of Symphonia is in the background, and if you are using a controller you don't really need keyboard input anyway.  And by keeping BlockWindows=False , the controller continues to work fine.  Also by keeping the settings this way, the input icons don't get confused and switch to keyboard icons, thus they remain as gamepad icons throughout the game.

```
[TSFix.Input]
BlockLeftAlt=false
BlockLeftCtrl=false
BlockWindows=false
BlockAllKeys=true
```
