### ISSUE TITLE
x360ce

### ISSUE THREAD

**Issue by sucht** [Kaldaien/TSF#6]
Tales of Symphonia "Fix" - v 0.9.0 Test3, is not working with x360ce, i always get the "Metal Gear Solid" sound when i try to start/run the game. when i remove the x360ce files the game starts and i can play.

this is what i put in the "d3d9.ini":
[Import.x360ce]
Architecture=Win32
Filename=xinput1_3.dll
Role=ThirdParty
When=Early

do i need to change something?

anyway thank you for tsfix :)

**Comment by Kaldaien** [comment]
Yeah, don't do that :) The DLL will be loaded twice if you do that.

It's probably crashing because x360ce does not expect to be loaded twice. Nevertheless, the answer is in logs/crash.log
